### PR TITLE
Remove static methods: Negate

### PR DESCRIPTION
**Pull request by shargon**
In order to improve the dotnet standard migration and reduce the risk changes, I want to remove the static methods one by one

In this PR:
- Remove `public static T operator -(in Ta)`

### CODE REVIEW

**Comment by Jim8y** [comment]
why splitting them can reduce so called risk? what risk are you specifing and how splitting them can reduce them? did you take any special measurement?

**Comment by shargon** [comment]
> why splitting them can reduce so called risk? what risk are you specifing and how splitting them can reduce them? did you take any special measurement?

It's cryptography, we should take care about any change, if the review it's easier, it will be hard to have a mistake

**Comment by shargon** [comment]
@Jim8y Merge?

**Comment by shargon** [comment]
Closed in favor of https://github.com/neo-project/Neo.Cryptography.BLS12_381/pull/11

**Pull request closed without merging**
